import type { StudyPlanSeed } from "./types";

// Feature 51's 3 Study Plans — real itineraries across Learn, Practice, FF
// Collections, and the Playbook, not a question list alone (build-plan.md's
// own framing for why this is a real FF differentiator). Every href below
// points at a route that exists today: concept slugs/categories verified
// against scripts/seed/concepts.ts, playbook chapter slugs against
// content/interview-prep/playbook/**, Practice category slugs against
// features/practice/lib/practiceCategories.ts's PRACTICE_CATEGORIES.
export const STUDY_PLANS: StudyPlanSeed[] = [
  {
    slug: "1-week",
    title: "1 Week",
    durationLabel: "1 Week",
    hoursCommitment: "~2 hrs/day",
    description:
      "Cramming for a frontend interview coming up fast. Rapid-fire review of the highest-frequency questions, a focused deep dive into JavaScript, React, and Next.js, then a full day each on system design, behavioural prep, and your target company before the real thing.",
    orderIndex: 1,
    items: [
      // Days 1-4: FF 75 (10/day), JS coding reps (5/day), React coding reps
      // (5/day) — one card per collection/category, not one card per
      // question, with a rangeLabel pill marking today's slice. Nobody
      // clears a ~75-question collection or a 35-challenge category in a
      // day; this is the realistic middle ground between "link the whole
      // collection" (the old version) and "one row per question" (147+ rows,
      // tried and rejected). Ranges progress in lockstep across JS and React
      // from Day 1 — someone with a week has no runway to finish JS before
      // touching React, so both build in parallel all week.
      {
        groupLabel: "Day 1",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q1 – Q10",
        title: "FF 75 rapid revision",
        description:
          "The 75 most-frequently-asked frontend interview questions, curated across JavaScript, React, and Next.js. Today's slice: the first 10. Flag anything you can't answer in under a minute — that's what tonight's review is for.",
      },
      {
        groupLabel: "Day 1",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q1 – Q5",
        title: "JavaScript coding reps",
        description: "Timed practice on real JavaScript coding challenges — closures, async patterns, array methods. 5 problems today; pair theory with hands-on speed.",
      },
      {
        groupLabel: "Day 1",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q1 – Q5",
        title: "React coding reps",
        description: "Real React coding challenges — custom hooks, state, component patterns. 5 problems today, building alongside your JavaScript reps all week.",
      },
      {
        groupLabel: "Day 1",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/search-autocomplete",
        title: "Designing a Real-Time Search Autocomplete",
        description: "One well-chosen system design guide a day, not the full library. Autocomplete is the single most commonly asked frontend system design prompt — debouncing, request cancellation, and caching in one compact problem.",
      },

      {
        groupLabel: "Day 2",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q11 – Q20",
        title: "FF 75 rapid revision",
        description: "Today's slice: questions 11 through 20. Keep flagging weak spots — you'll hit them again in Sunday's final review.",
      },
      {
        groupLabel: "Day 2",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q6 – Q10",
        title: "JavaScript coding reps",
        description: "5 more JavaScript problems, picking up right where yesterday's reps left off.",
      },
      {
        groupLabel: "Day 2",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q6 – Q10",
        title: "React coding reps",
        description: "5 more React problems — hooks and component patterns keep building alongside JavaScript.",
      },
      {
        groupLabel: "Day 2",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/reusable-modal-dialog-system",
        title: "Designing a Reusable Modal and Dialog System",
        description: "A near-guaranteed \"build a component system\" prompt — focus management, portals, and stacking context, asked in some form at almost every frontend loop.",
      },

      {
        groupLabel: "Day 3",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q21 – Q30",
        title: "FF 75 rapid revision",
        description: "Today's slice: questions 21 through 30 — you're a third of the way through the collection.",
      },
      {
        groupLabel: "Day 3",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q11 – Q15",
        title: "JavaScript coding reps",
        description: "5 more JavaScript problems, continuing the sequence from Day 2.",
      },
      {
        groupLabel: "Day 3",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q11 – Q15",
        title: "React coding reps",
        description: "5 more React problems, continuing the sequence from Day 2.",
      },
      {
        groupLabel: "Day 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/infinite-scroll-feed",
        title: "Designing an Infinite-Scroll Feed",
        description: "One of the most frequently cited frontend system design prompts — pagination strategy, scroll performance, and when infinite scroll is actually the wrong call.",
      },

      {
        groupLabel: "Day 4",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q31 – Q40",
        title: "FF 75 rapid revision",
        description: "Today's slice: questions 31 through 40 — past the halfway point of the FF 75.",
      },
      {
        groupLabel: "Day 4",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q16 – Q20",
        title: "JavaScript coding reps",
        description: "5 more JavaScript problems, continuing the sequence from Day 3.",
      },
      {
        groupLabel: "Day 4",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q16 – Q20",
        title: "React coding reps",
        description: "5 more React problems, continuing the sequence from Day 3.",
      },
      {
        groupLabel: "Day 4",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/photo-sharing-feed",
        title: "Designing a Photo-Sharing Feed and Gallery",
        description: "Media-heavy feed design — lazy loading, responsive image strategy, and layout shift, a recurring theme across e-commerce and social-app interviews alike.",
      },

      {
        groupLabel: "Day 5",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q41 – Q50",
        title: "FF 75 rapid revision",
        description: "Today's slice: questions 41 through 50.",
      },
      {
        groupLabel: "Day 5",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q21 – Q25",
        title: "JavaScript coding reps",
        description: "5 more JavaScript problems, continuing the sequence from Day 4.",
      },
      {
        groupLabel: "Day 5",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q21 – Q25",
        title: "React coding reps",
        description: "5 more React problems, continuing the sequence from Day 4.",
      },
      {
        groupLabel: "Day 5",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/social-news-feed",
        title: "Designing a Personalized Social News Feed",
        description: "The classic Twitter/Facebook-style feed prompt — ranking, real-time updates, and normalization, one of the two or three most commonly asked frontend system design questions.",
      },
      {
        groupLabel: "Day 5",
        itemType: "playbook-chapter",
        refId: "frontend-system-design-playbook/why-frontend-system-design-is-different",
        href: "/interview-prep/playbook/frontend-system-design-playbook/why-frontend-system-design-is-different",
        title: "Why frontend system design is different",
        description: "How frontend system design interviews diverge from backend ones — read this once you've got a few real guides under your belt, so the framework has something to attach to.",
      },

      {
        groupLabel: "Day 6",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q51 – Q60",
        title: "FF 75 rapid revision",
        description: "Today's slice: questions 51 through 60.",
      },
      {
        groupLabel: "Day 6",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q26 – Q30",
        title: "JavaScript coding reps",
        description: "5 more JavaScript problems, continuing the sequence from Day 5.",
      },
      {
        groupLabel: "Day 6",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q26 – Q30",
        title: "React coding reps",
        description: "5 more React problems, continuing the sequence from Day 5.",
      },
      {
        groupLabel: "Day 6",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/realtime-messaging-client",
        title: "Designing a Real-Time Messaging Client",
        description: "WebSockets, optimistic updates, and message ordering — a real-time chat prompt that shows up constantly once a company's product involves any live communication.",
      },
      {
        groupLabel: "Day 6",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/the-star-method-done-properly",
        href: "/interview-prep/playbook/behavioural-interview-playbook/the-star-method-done-properly",
        title: "The STAR method, done properly",
        description: "How to structure a behavioural answer so it lands — the concrete Action-to-Situation ratio most candidates get backwards.",
      },
      {
        groupLabel: "Day 6",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/building-your-personal-story-bank",
        href: "/interview-prep/playbook/behavioural-interview-playbook/building-your-personal-story-bank",
        title: "Build your personal story bank",
        description: "Turn your last few projects into 5-6 reusable STAR stories you can adapt on the fly to almost any behavioural prompt.",
      },

      {
        groupLabel: "Day 7",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q61 – Q75",
        title: "FF 75 rapid revision",
        description: "The home stretch: questions 61 through 75, closing out the full FF 75 the night before you walk in.",
      },
      {
        groupLabel: "Day 7",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q31 – Q35",
        title: "JavaScript coding reps",
        description: "The final 5 JavaScript problems, closing out 35 for the week.",
      },
      {
        groupLabel: "Day 7",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q31 – Q35",
        title: "React coding reps",
        description: "The final 5 React problems, closing out 35 for the week.",
      },
      {
        groupLabel: "Day 7",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/video-streaming-player",
        title: "Designing a Video Streaming Player",
        description: "Buffering strategy, adaptive bitrate, and playback state — a YouTube-style prompt that closes out the week on one of the harder, higher-signal guides.",
      },
      {
        groupLabel: "Day 7",
        itemType: "company-guide",
        href: "/interview-prep/company-guides",
        title: "Target company guide",
        description: "Find your target company and review the real questions and challenges attributed to it — the single highest-leverage hour before an on-site.",
      },
      {
        groupLabel: "Day 7",
        itemType: "review-session",
        href: "/interview-prep/review",
        title: "Final spaced-repetition review",
        description: "A last spaced-repetition pass over everything you've rated this week — the questions you marked \"Need to review\" surface first.",
      },
    ],
  },

  {
    slug: "1-month",
    title: "1 Month",
    durationLabel: "1 Month",
    hoursCommitment: "~6 hrs/week",
    description:
      "Goal: go from shaky fundamentals to interview-ready in 4 weeks — Week 1 locks down the JavaScript concepts that gate everything else, Week 2 does the same for React, Week 3 broadens into TypeScript and Next.js, and Week 4 shifts fully into interview mode. Every week also carries 3 real FF Frontend System Design questions and a slice of the FF 75, so system design and rapid review build continuously rather than landing all at once at the end.",
    orderIndex: 2,
    items: [
      // Week 1 — JavaScript foundations. The 5 concepts below gate almost
      // everything else asked in a JS-heavy loop (closures and the event
      // loop especially) — deliberately covered before any other category.
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "javascript-runtime/hoisting-temporal-dead-zone",
        href: "/learn/javascript-runtime/hoisting-temporal-dead-zone",
        title: "Learn: Hoisting & the Temporal Dead Zone",
        description: "How var, let, const, and function declarations are hoisted differently — a near-guaranteed \"what does this log?\" warm-up question.",
      },
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "javascript-runtime/closures",
        href: "/learn/javascript-runtime/closures",
        title: "Learn: Closures",
        description: "The concept behind more JavaScript \"gotcha\" interview questions than almost any other — worth getting genuinely solid on, not just familiar with.",
      },
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "javascript-runtime/callbacks-higher-order-functions",
        href: "/learn/javascript-runtime/callbacks-higher-order-functions",
        title: "Learn: Callbacks & Higher-Order Functions",
        description: "Functions that accept or return other functions — the pattern underneath event handlers, array methods, and every async API you'll touch this week.",
      },
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "javascript-runtime/event-loop",
        href: "/learn/javascript-runtime/event-loop",
        title: "Learn: Event Loop",
        description: "Call stack, task queue, microtask queue — how single-threaded JavaScript handles async work. One of the most commonly whiteboarded JS topics.",
      },
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "javascript-runtime/promises-async-await",
        href: "/learn/javascript-runtime/promises-async-await",
        title: "Learn: Promises & Async/Await",
        description: "Pending/fulfilled/rejected states, and why async/await is just syntax over the same mechanism — closes out this week's JavaScript core.",
      },
      {
        groupLabel: "Week 1",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q1 – Q20",
        title: "FF 75 rapid revision",
        description: "Today's week's slice: the first 20 of the FF 75, spread across JavaScript, React, and Next.js. A continuous thread across all 4 weeks, not a single end-of-month cram.",
      },
      {
        groupLabel: "Week 1",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        rangeLabel: "Solve Q1 – Q20",
        title: "FF JavaScript deep dive",
        description: "Beyond the FF 75 subset — the full 101-question JavaScript collection, paired with this week's Learn concepts.",
      },
      {
        groupLabel: "Week 1",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q1 – Q40",
        title: "JavaScript coding reps",
        description: "Hands-on coding reps — closures, async patterns, array methods — putting this week's concepts into your fingers, not just your head.",
      },
      {
        groupLabel: "Week 1",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/star-rating-widget",
        title: "Designing a Star Rating Widget",
        description: "A deliberately small, component-scale system design warm-up — accessible keyboard interaction and hover state on a component you've actually used.",
      },
      {
        groupLabel: "Week 1",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/accessible-dropdown-menu",
        title: "Designing an Accessible Dropdown Menu Component",
        description: "One of the most commonly asked \"build a component system\" prompts — focus management and ARIA roles on a component every design system needs.",
      },
      {
        groupLabel: "Week 1",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/positioning-aware-tooltip-popover",
        title: "Designing a Positioning-Aware Tooltip and Popover System",
        description: "Viewport-collision handling for tooltips and popovers — a recurring UI-component system design prompt across frontend loops.",
      },

      // Week 2 — React. Same shape as Week 1: concepts first, then FF 75 +
      // the deeper FF React collection + coding reps + 3 system design guides.
      {
        groupLabel: "Week 2",
        itemType: "concept",
        refId: "react/jsx-virtual-dom",
        href: "/learn/react/jsx-virtual-dom",
        title: "Learn: JSX & the Virtual DOM",
        description: "React week starts here — how JSX compiles to a Virtual DOM tree, the mental model every later React concept builds on.",
      },
      {
        groupLabel: "Week 2",
        itemType: "concept",
        refId: "react/usestate-useeffect-fundamentals",
        href: "/learn/react/usestate-useeffect-fundamentals",
        title: "Learn: useState & useEffect Fundamentals",
        description: "The two hooks every component starts with, and the dependency-array rules that trip up even experienced React developers in interviews.",
      },
      {
        groupLabel: "Week 2",
        itemType: "concept",
        refId: "react/controlled-vs-uncontrolled-forms",
        href: "/learn/react/controlled-vs-uncontrolled-forms",
        title: "Learn: Forms — Controlled vs. Uncontrolled",
        description: "Inputs React owns via state vs. inputs that manage their own value via refs — a standard \"build a form\" live-coding topic.",
      },
      {
        groupLabel: "Week 2",
        itemType: "concept",
        refId: "react/context-api-prop-drilling",
        href: "/learn/react/context-api-prop-drilling",
        title: "Learn: Context API & Prop Drilling",
        description: "How Context lets any descendant read shared state directly, and when reaching for it is the wrong call.",
      },
      {
        groupLabel: "Week 2",
        itemType: "concept",
        refId: "react/react-rendering",
        href: "/learn/react/react-rendering",
        title: "Learn: React Rendering & Reconciliation",
        description: "How React's reconciler decides what to re-render and diffs the Virtual DOM — the concept behind almost every React performance question.",
      },
      {
        groupLabel: "Week 2",
        itemType: "concept",
        refId: "react/state-management-tradeoffs",
        href: "/learn/react/state-management-tradeoffs",
        title: "Learn: State Management Tradeoffs",
        description: "Local state vs. Context vs. external stores — closes out React week with the architectural question senior-leaning loops actually ask.",
      },
      {
        groupLabel: "Week 2",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q21 – Q40",
        title: "FF 75 rapid revision",
        description: "This week's slice: questions 21 through 40 — the FF 75 keeps moving alongside React week.",
      },
      {
        groupLabel: "Week 2",
        itemType: "collection",
        href: "/interview-prep/ff-react",
        rangeLabel: "Solve Q1 – Q20",
        title: "FF React deep dive",
        description: "The full 99-question React collection — hooks, rendering, and component patterns beyond the FF 75 subset.",
      },
      {
        groupLabel: "Week 2",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q1 – Q30",
        title: "React coding reps",
        description: "Custom hooks, component patterns, and state — hands-on React reps pairing this week's concepts with real code.",
      },
      {
        groupLabel: "Week 2",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/ecommerce-storefront",
        title: "Designing a High-Traffic E-Commerce Storefront",
        description: "Product listings, cart state, and checkout flow — a React-state-heavy system design prompt that shows up constantly at product companies.",
      },
      {
        groupLabel: "Week 2",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/scalable-design-system",
        title: "Designing a Scalable Frontend Design System",
        description: "Component API design and theming at scale — a natural pairing with this week's Context API and composition concepts.",
      },
      {
        groupLabel: "Week 2",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/multiplayer-document-editor",
        title: "Designing a Multiplayer Collaborative Document Editor",
        description: "A Google Docs-style prompt — one of the most frequently cited \"real-time collaborative\" system design questions, and a harder closer for React week.",
      },

      // Week 3 — Breadth: TypeScript + the deeper Next.js collection.
      // Deliberately no CSS this week — TypeScript and Next.js are the two
      // categories a JS/React-only prep plan otherwise skips.
      {
        groupLabel: "Week 3",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q41 – Q60",
        title: "FF 75 rapid revision",
        description: "This week's slice: questions 41 through 60 — three-quarters of the way through the FF 75.",
      },
      {
        groupLabel: "Week 3",
        itemType: "collection",
        href: "/interview-prep/ff-nextjs",
        rangeLabel: "Solve Q1 – Q20",
        title: "FF Next.js deep dive",
        description: "Rendering strategies, routing, and the App Router — the full 99-question Next.js collection most JavaScript-only prep skips entirely.",
      },
      {
        groupLabel: "Week 3",
        itemType: "practice-category",
        href: "/practice/typescript",
        rangeLabel: "Solve Q1 – Q15",
        title: "TypeScript coding reps",
        description: "Type-level problems graded against the real TypeScript compiler — the category most JS/React-only prep never touches.",
      },
      {
        groupLabel: "Week 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/realtime-task-tracker",
        title: "Designing a Real-Time Collaborative Task Tracker",
        description: "A Trello-style kanban board prompt — drag-and-drop state, optimistic updates, and multi-user sync in one common system design question.",
      },
      {
        groupLabel: "Week 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/rich-text-editor-engine",
        title: "Designing a Rich Text Editor Engine",
        description: "contentEditable, selection state, and a document model — a recurring \"build a Notion/Google Docs editor\" prompt.",
      },
      {
        groupLabel: "Week 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/collaborative-spreadsheet-engine",
        title: "Designing a Real-Time Collaborative Spreadsheet Engine",
        description: "Formula recalculation and cell-level real-time sync — a harder, data-heavy closer for breadth week.",
      },

      // Week 4 — Interview mode: close out the FF 75, behavioural + resume
      // prep, your target company, and a final review pass.
      {
        groupLabel: "Week 4",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        rangeLabel: "Solve Q61 – Q75",
        title: "FF 75 rapid revision",
        description: "The final slice: questions 61 through 75, closing out the full FF 75 by the end of the month.",
      },
      {
        groupLabel: "Week 4",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/the-star-method-done-properly",
        href: "/interview-prep/playbook/behavioural-interview-playbook/the-star-method-done-properly",
        title: "The STAR method, done properly",
        description: "Behavioural prep week — structure your answers before you write them.",
      },
      {
        groupLabel: "Week 4",
        itemType: "playbook-chapter",
        refId: "frontend-resume-playbook/frontend-specific-resume-structure",
        href: "/interview-prep/playbook/frontend-resume-playbook/frontend-specific-resume-structure",
        title: "Frontend-specific resume structure",
        description: "Tighten your resume against what frontend recruiters actually scan for, before you start applying.",
      },
      {
        groupLabel: "Week 4",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/travel-search-and-booking",
        title: "Designing a Travel Search and Booking Flow",
        description: "A complex multi-step form/booking flow — filters, date ranges, and multi-step validation in one comprehensive prompt.",
      },
      {
        groupLabel: "Week 4",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/browser-video-conferencing",
        title: "Designing a Browser-Based Video Conferencing App",
        description: "A Zoom/Meet-style prompt — WebRTC signaling and media stream management, a harder guide fit for the final stretch.",
      },
      {
        groupLabel: "Week 4",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/offline-first-sync-engine",
        title: "Designing an Offline-First Local Sync Engine",
        description: "Local writes, conflict resolution, and background sync — the hardest guide of the month, closing out system design prep.",
      },
      {
        groupLabel: "Week 4",
        itemType: "company-guide",
        href: "/interview-prep/company-guides",
        title: "Target company guide",
        description: "Filter down to real questions and challenges from your target company — the highest-leverage hour before you start interviewing.",
      },
      {
        groupLabel: "Week 4",
        itemType: "review-session",
        href: "/interview-prep/review",
        title: "Spaced-repetition review",
        description: "A full pass over everything you've rated across the month — the questions you marked \"Need to review\" surface first.",
      },
    ],
  },

  {
    slug: "3-months",
    title: "3 Months",
    durationLabel: "3 Months",
    hoursCommitment: "~2 hrs/day",
    description:
      "Goal: build real depth, not just breadth. Month 1 gives JavaScript and React a full core-then-advanced pass each — the two categories that dominate real interview loops. Month 2 covers every remaining Learn category and walks all 3 real FF Collections (JavaScript, React, Next.js) straight through, once, with zero repeats — no FF 75 here, that's a 1-2 week cram tool, not a 3-month depth plan. Month 3 shifts fully into interview mode: System Design concepts and guides, a Playbook sweep, your target Company Guide, and a final review.",
    orderIndex: 3,
    items: [
      // ── Month 1 — JavaScript & React, core then advanced. These two
      // categories dominate real interview loops, so they get double the
      // calendar time (2 weeks each) that every other category gets (1 week).
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/hoisting-temporal-dead-zone",
        href: "/learn/javascript-runtime/hoisting-temporal-dead-zone",
        title: "Learn: Hoisting & the Temporal Dead Zone",
        description: "Month 1 is JavaScript, core then advanced, followed by React, core then advanced — the two categories that dominate real interview loops get double the time.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/closures",
        href: "/learn/javascript-runtime/closures",
        title: "Learn: Closures",
        description: "The concept behind more \"gotcha\" interview questions than almost any other in JavaScript.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/callbacks-higher-order-functions",
        href: "/learn/javascript-runtime/callbacks-higher-order-functions",
        title: "Learn: Callbacks & Higher-Order Functions",
        description: "Functions that accept or return other functions — the pattern underneath event handlers, array methods, and every async API.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/event-loop",
        href: "/learn/javascript-runtime/event-loop",
        title: "Learn: Event Loop",
        description: "Call stack, task queue, microtask queue — one of the most commonly whiteboarded JS topics.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/promises-async-await",
        href: "/learn/javascript-runtime/promises-async-await",
        title: "Learn: Promises & Async/Await",
        description: "Pending/fulfilled/rejected states, and why async/await is syntax over the same mechanism.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q1 – Q30",
        title: "JavaScript coding reps",
        description: "Hands-on coding reps — closures, async patterns, array methods — putting this week's concepts into your fingers, not just your head.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        rangeLabel: "Solve Q1 – Q40",
        title: "FF JavaScript deep dive",
        description: "The full 101-question JavaScript collection, walked through once, straight through — no FF 75 shortcut here.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/search-autocomplete",
        title: "Designing a Real-Time Search Autocomplete",
        description: "The single most commonly cited frontend system design prompt — debouncing, request cancellation, and caching.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/reusable-modal-dialog-system",
        title: "Designing a Reusable Modal and Dialog System",
        description: "Focus management, portals, and stacking context — a near-guaranteed component-system prompt.",
      },

      {
        groupLabel: "Month 1 · Week 2",
        itemType: "concept",
        refId: "javascript-runtime/this-binding-execution-context",
        href: "/learn/javascript-runtime/this-binding-execution-context",
        title: "Learn: this Binding & Execution Context",
        description: "JavaScript advanced: how this is determined at call time, and why arrow functions are the exception.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "concept",
        refId: "javascript-runtime/prototypal-inheritance",
        href: "/learn/javascript-runtime/prototypal-inheritance",
        title: "Learn: Prototypal Inheritance",
        description: "How every object links to a prototype, and what class/extends really compiles down to.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "concept",
        refId: "javascript-runtime/array-object-methods-immutability",
        href: "/learn/javascript-runtime/array-object-methods-immutability",
        title: "Learn: Array & Object Methods, Immutability",
        description: "map, filter, reduce, and why returning new data instead of mutating in place keeps state predictable.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "concept",
        refId: "javascript-runtime/debouncing-throttling",
        href: "/learn/javascript-runtime/debouncing-throttling",
        title: "Learn: Debouncing & Throttling",
        description: "The two standard fixes for handlers that fire too often, and when to reach for each — closes out JavaScript.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q31 – Q60",
        title: "JavaScript coding reps",
        description: "More coding reps, continuing straight from Week 1's Q1–30.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        rangeLabel: "Solve Q41 – Q80",
        title: "FF JavaScript deep dive",
        description: "Continuing the JavaScript collection from where Week 1 left off.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/star-rating-widget",
        title: "Designing a Star Rating Widget",
        description: "A small, component-scale warm-up — accessible keyboard interaction on a component you've actually used.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/accessible-dropdown-menu",
        title: "Designing an Accessible Dropdown Menu Component",
        description: "Focus management and ARIA roles on a component every design system needs.",
      },

      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/jsx-virtual-dom",
        href: "/learn/react/jsx-virtual-dom",
        title: "Learn: JSX & the Virtual DOM",
        description: "React week starts here — the mental model every later React concept builds on.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/usestate-useeffect-fundamentals",
        href: "/learn/react/usestate-useeffect-fundamentals",
        title: "Learn: useState & useEffect Fundamentals",
        description: "The two hooks every component starts with, and the dependency-array rules that trip up interviews.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/controlled-vs-uncontrolled-forms",
        href: "/learn/react/controlled-vs-uncontrolled-forms",
        title: "Learn: Forms — Controlled vs. Uncontrolled",
        description: "Inputs React owns via state vs. inputs that manage their own value via refs.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/context-api-prop-drilling",
        href: "/learn/react/context-api-prop-drilling",
        title: "Learn: Context API & Prop Drilling",
        description: "How Context lets any descendant read shared state directly, and when reaching for it is the wrong call.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/react-rendering",
        href: "/learn/react/react-rendering",
        title: "Learn: React Rendering & Reconciliation",
        description: "How React's reconciler decides what to re-render — the concept behind almost every React performance question.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/state-management-tradeoffs",
        href: "/learn/react/state-management-tradeoffs",
        title: "Learn: State Management Tradeoffs",
        description: "Local state vs. Context vs. external stores — closes out React core.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q1 – Q18",
        title: "React coding reps",
        description: "Custom hooks, component patterns, and state — hands-on React reps pairing this week's concepts with real code.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "collection",
        href: "/interview-prep/ff-react",
        rangeLabel: "Solve Q1 – Q40",
        title: "FF React deep dive",
        description: "The full 99-question React collection, walked through once, straight through.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/positioning-aware-tooltip-popover",
        title: "Designing a Positioning-Aware Tooltip and Popover System",
        description: "Viewport-collision handling for tooltips and popovers — a recurring UI-component prompt.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/accessible-image-carousel",
        title: "Designing an Accessible Image Carousel",
        description: "Keyboard-navigable, screen-reader-friendly carousel patterns — closes out the easier system design guides.",
      },

      {
        groupLabel: "Month 1 · Week 4",
        itemType: "concept",
        refId: "react/useref-imperative-handles",
        href: "/learn/react/useref-imperative-handles",
        title: "Learn: useRef & Imperative Handles",
        description: "React advanced: how useRef holds a mutable value across renders without triggering one.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "concept",
        refId: "react/component-composition-patterns",
        href: "/learn/react/component-composition-patterns",
        title: "Learn: Component Composition Patterns",
        description: "Composing components instead of configuring them with props — a senior-leaning React interview topic.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "concept",
        refId: "react/custom-hooks-composition",
        href: "/learn/react/custom-hooks-composition",
        title: "Learn: Custom Hooks & Composition",
        description: "Extracting reusable stateful logic into your own hooks — a standard \"refactor this\" interview exercise.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "concept",
        refId: "react/render-performance-memoization",
        href: "/learn/react/render-performance-memoization",
        title: "Learn: Render Performance — memo, useMemo, useCallback",
        description: "When memoization actually helps vs. when it's dead weight — closes out React.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "practice-category",
        href: "/practice/react",
        rangeLabel: "Solve Q19 – Q35",
        title: "React coding reps",
        description: "More React reps, continuing from Week 3's Q1–18 — 35 of 38 challenges by the end of this week.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "collection",
        href: "/interview-prep/ff-react",
        rangeLabel: "Solve Q41 – Q80",
        title: "FF React deep dive",
        description: "Continuing the React collection from where Week 3 left off.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/ecommerce-storefront",
        title: "Designing a High-Traffic E-Commerce Storefront",
        description: "Product listings, cart state, and checkout flow — a React-state-heavy prompt to close out Month 1.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/scalable-design-system",
        title: "Designing a Scalable Frontend Design System",
        description: "Component API design and theming at scale — pairs naturally with this week's composition concepts.",
      },

      // ── Month 2 — Every remaining Learn category, and every FF Collection
      // finished exactly once, with zero repeats (no FF 75 in this plan).
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "concept",
        refId: "browser-internals/dom-vs-bom",
        href: "/learn/browser-internals/dom-vs-bom",
        title: "Learn: DOM vs. BOM",
        description: "Month 2 covers Browser Internals, CSS, TypeScript, and Accessibility + Performance — one week each.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "concept",
        refId: "browser-internals/event-delegation-bubbling-capturing",
        href: "/learn/browser-internals/event-delegation-bubbling-capturing",
        title: "Learn: Event Delegation, Bubbling & Capturing",
        description: "A near-guaranteed live-coding or whiteboard topic in any frontend loop.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "concept",
        refId: "browser-internals/browser-rendering-pipeline",
        href: "/learn/browser-internals/browser-rendering-pipeline",
        title: "Learn: Browser Rendering Pipeline",
        description: "DOM, CSSOM, Render Tree, Layout, Paint, Composite — how a browser turns markup into pixels.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "concept",
        refId: "browser-internals/web-security-fundamentals",
        href: "/learn/browser-internals/web-security-fundamentals",
        title: "Learn: Web Security Fundamentals (XSS, CSRF, CSP)",
        description: "The three attacks every frontend has to defend against, and how CSP/sanitization/same-site cookies stop them.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        rangeLabel: "Solve Q61 – Q90",
        title: "JavaScript coding reps",
        description: "Continuing JavaScript reps here since Browser Internals has no dedicated Practice category of its own.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        rangeLabel: "Solve Q81 – Q101",
        title: "FF JavaScript deep dive",
        description: "The final slice — finishes the full 101-question JavaScript collection.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/infinite-scroll-feed",
        title: "Designing an Infinite-Scroll Feed",
        description: "Pagination strategy and scroll performance — one of the most frequently cited system design prompts.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/photo-sharing-feed",
        title: "Designing a Photo-Sharing Feed and Gallery",
        description: "Lazy loading and responsive image strategy — a recurring theme across e-commerce and social apps.",
      },

      {
        groupLabel: "Month 2 · Week 6",
        itemType: "concept",
        refId: "css/the-box-model",
        href: "/learn/css/the-box-model",
        title: "Learn: The Box Model",
        description: "CSS week — the model every layout question, from Flexbox to Grid, builds on.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "concept",
        refId: "css/css-specificity",
        href: "/learn/css/css-specificity",
        title: "Learn: CSS Specificity",
        description: "The single most commonly misunderstood CSS interview topic — worth a real deep dive.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "concept",
        refId: "css/flexbox-vs-grid",
        href: "/learn/css/flexbox-vs-grid",
        title: "Learn: Flexbox vs. Grid",
        description: "When to reach for one-dimensional Flexbox vs. two-dimensional Grid — a standard live-coding layout question.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "concept",
        refId: "css/responsive-design-container-queries",
        href: "/learn/css/responsive-design-container-queries",
        title: "Learn: Responsive Design & Container Queries",
        description: "Media queries vs. the newer container-query model — closes out CSS.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "practice-category",
        href: "/practice/css",
        rangeLabel: "Solve Q1 – Q30",
        title: "CSS coding reps",
        description: "Layout and specificity problems you can only get fast at through repetition.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "collection",
        href: "/interview-prep/ff-react",
        rangeLabel: "Solve Q81 – Q99",
        title: "FF React deep dive",
        description: "The final slice — finishes the full 99-question React collection.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/masonry-discovery-feed",
        title: "Designing a Masonry-Style Visual Discovery Feed",
        description: "Pinterest-style layout packing — a natural pairing with this week's Flexbox/Grid concepts.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/i18n-l10n-architecture",
        title: "Designing an Internationalization and Localization Architecture",
        description: "Locale-aware formatting and layout — a genuinely different kind of \"CSS at scale\" problem.",
      },

      {
        groupLabel: "Month 2 · Week 7",
        itemType: "concept",
        refId: "typescript/basic-types-inference",
        href: "/learn/typescript/basic-types-inference",
        title: "Learn: Basic Types, Inference & any/unknown/never",
        description: "TypeScript week — the category most JS/React-only prep skips entirely.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "concept",
        refId: "typescript/interfaces-vs-type-aliases",
        href: "/learn/typescript/interfaces-vs-type-aliases",
        title: "Learn: Interfaces vs. Type Aliases",
        description: "A near-guaranteed question in any TypeScript-heavy interview loop.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "concept",
        refId: "typescript/generics",
        href: "/learn/typescript/generics",
        title: "Learn: Generics",
        description: "Writing reusable, type-safe functions and components without falling back to any.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "concept",
        refId: "typescript/utility-types",
        href: "/learn/typescript/utility-types",
        title: "Learn: Utility Types (Partial, Pick, Omit, Record)",
        description: "The built-in type transformations that show up in almost every TypeScript codebase — closes out TypeScript.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "practice-category",
        href: "/practice/typescript",
        rangeLabel: "Solve Q1 – Q45",
        title: "TypeScript coding reps",
        description: "Type-level problems graded against the real TypeScript compiler, not string matching.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "collection",
        href: "/interview-prep/ff-nextjs",
        rangeLabel: "Solve Q1 – Q50",
        title: "FF Next.js deep dive",
        description: "Rendering strategies, routing, and the App Router — the full 99-question Next.js collection starts here.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/ai-assisted-frontend-feature",
        title: "Designing an AI-Assisted Frontend Feature",
        description: "Streaming responses and optimistic UI for an LLM-backed feature — an increasingly common modern prompt.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/audio-streaming-player",
        title: "Designing an Audio Streaming Player",
        description: "Buffering and playback state for audio — a lighter sibling of the video-streaming prompt later this plan.",
      },

      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "accessibility/aria-roles-and-semantic-html",
        href: "/learn/accessibility/aria-roles-and-semantic-html",
        title: "Learn: Semantic HTML & ARIA Roles",
        description: "Accessibility + Performance, combined into one week — neither has its own Practice category.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "accessibility/keyboard-navigation-focus-management",
        href: "/learn/accessibility/keyboard-navigation-focus-management",
        title: "Learn: Keyboard Navigation & Focus Management",
        description: "Focus traps, roving tabindex, and skip links — the accessibility work interviewers actually check for live.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "accessibility/accessible-forms",
        href: "/learn/accessibility/accessible-forms",
        title: "Learn: Accessible Forms",
        description: "Label association, error announcement, and fieldset grouping — closes out Accessibility.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "performance/image-asset-optimization",
        href: "/learn/performance/image-asset-optimization",
        title: "Learn: Image & Asset Optimization",
        description: "Performance — the easiest wins to talk through concretely in an interview.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "performance/bundle-size-code-splitting",
        href: "/learn/performance/bundle-size-code-splitting",
        title: "Learn: Bundle Size & Code Splitting",
        description: "How to talk about performance like a senior engineer — with real levers, not vague claims.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "performance/core-web-vitals",
        href: "/learn/performance/core-web-vitals",
        title: "Learn: Core Web Vitals",
        description: "LCP, INP, and CLS — the concrete numbers behind \"the site feels slow,\" and closes out Month 2's Learn concepts.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "collection",
        href: "/interview-prep/ff-nextjs",
        rangeLabel: "Solve Q51 – Q99",
        title: "FF Next.js deep dive",
        description: "The final slice — finishes the full 99-question Next.js collection. All 299 real collection questions are now covered, once, no repeats.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/realtime-task-tracker",
        title: "Designing a Real-Time Collaborative Task Tracker",
        description: "A Trello-style kanban board — drag-and-drop state and multi-user sync.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/rich-text-editor-engine",
        title: "Designing a Rich Text Editor Engine",
        description: "contentEditable, selection state, and a document model — closes out Month 2's system design guides.",
      },

      // ── Month 3 — Interview mode: System Design concepts + guides, a
      // Playbook sweep, your target Company Guide, and a final review.
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "concept",
        refId: "system-design/component-driven-architecture",
        href: "/learn/system-design/component-driven-architecture",
        title: "Learn: Component-Driven Architecture",
        description: "Month 3 shifts fully into interview mode — System Design concepts and guides, all 6 Playbooks, and your target Company Guide.",
      },
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "practice-category",
        href: "/practice/system-design",
        rangeLabel: "Solve Q1 – Q25",
        title: "System Design coding reps",
        description: "Applied system-design problems to pressure-test this week's concept and every guide you've read so far.",
      },
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/travel-search-and-booking",
        title: "Designing a Travel Search and Booking Flow",
        description: "A complex multi-step form — filters, date ranges, and multi-step validation.",
      },
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/social-news-feed",
        title: "Designing a Personalized Social News Feed",
        description: "The classic Twitter/Facebook-style feed — ranking, real-time updates, and normalization.",
      },
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "playbook-chapter",
        refId: "frontend-system-design-playbook/a-repeatable-framework-for-frontend-system-design",
        href: "/interview-prep/playbook/frontend-system-design-playbook/a-repeatable-framework-for-frontend-system-design",
        title: "A repeatable framework for frontend system design",
        description: "The requirements-to-tradeoffs framework this playbook uses — apply it to every guide you've read so far.",
      },

      {
        groupLabel: "Month 3 · Week 10",
        itemType: "concept",
        refId: "system-design/api-design-data-fetching-strategy",
        href: "/learn/system-design/api-design-data-fetching-strategy",
        title: "Learn: API Design & Data-Fetching Strategy",
        description: "REST vs. GraphQL vs. WebSockets, and how to reason about the tradeoffs out loud.",
      },
      {
        groupLabel: "Month 3 · Week 10",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/realtime-messaging-client",
        title: "Designing a Real-Time Messaging Client",
        description: "WebSockets, optimistic updates, and message ordering — a real-time chat prompt.",
      },
      {
        groupLabel: "Month 3 · Week 10",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/video-streaming-player",
        title: "Designing a Video Streaming Player",
        description: "Buffering strategy, adaptive bitrate, and playback state — a YouTube-style prompt.",
      },
      {
        groupLabel: "Month 3 · Week 10",
        itemType: "playbook-chapter",
        refId: "frontend-interview-playbook/how-frontend-interviews-are-structured",
        href: "/interview-prep/playbook/frontend-interview-playbook/how-frontend-interviews-are-structured",
        title: "How frontend interviews are structured",
        description: "The Playbook sweep starts here — the format overview every other chapter builds on.",
      },

      {
        groupLabel: "Month 3 · Week 11",
        itemType: "concept",
        refId: "system-design/frontend-architecture-patterns",
        href: "/learn/system-design/frontend-architecture-patterns",
        title: "Learn: Frontend Architecture Patterns",
        description: "Monoliths, micro-frontends, and modular monorepos — closes out System Design concepts.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/multiplayer-document-editor",
        title: "Designing a Multiplayer Collaborative Document Editor",
        description: "A Google Docs-style prompt — one of the most frequently cited real-time collaborative system design questions.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/collaborative-spreadsheet-engine",
        title: "Designing a Real-Time Collaborative Spreadsheet Engine",
        description: "Formula recalculation and cell-level real-time sync — one of the harder guides in the library.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/the-star-method-done-properly",
        href: "/interview-prep/playbook/behavioural-interview-playbook/the-star-method-done-properly",
        title: "The STAR method, done properly",
        description: "Behavioural prep — structure your answers before you write them.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/building-your-personal-story-bank",
        href: "/interview-prep/playbook/behavioural-interview-playbook/building-your-personal-story-bank",
        title: "Build your personal story bank",
        description: "Turn your last few projects into 5-6 reusable STAR stories you can adapt on the fly.",
      },

      {
        groupLabel: "Month 3 · Week 12",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/browser-video-conferencing",
        title: "Designing a Browser-Based Video Conferencing App",
        description: "A Zoom/Meet-style prompt — WebRTC signaling and media stream management.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design/offline-first-sync-engine",
        title: "Designing an Offline-First Local Sync Engine",
        description: "Local writes, conflict resolution, and background sync — the final, hardest guide of the plan.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "playbook-chapter",
        refId: "frontend-resume-playbook/frontend-specific-resume-structure",
        href: "/interview-prep/playbook/frontend-resume-playbook/frontend-specific-resume-structure",
        title: "Frontend-specific resume structure",
        description: "Tighten your resume against what frontend recruiters actually scan for, before you start applying.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "playbook-chapter",
        refId: "react-interview-playbook/what-react-interviews-really-test",
        href: "/interview-prep/playbook/react-interview-playbook/what-react-interviews-really-test",
        title: "What React interviews really test",
        description: "The React Interview Playbook's take on what actually gets scored in a React-focused loop.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "company-guide",
        href: "/interview-prep/company-guides",
        title: "Target company guide",
        description: "Real questions and challenges from your target company — the final, highest-leverage prep step.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "review-session",
        href: "/interview-prep/review",
        title: "Final spaced-repetition review",
        description: "One last pass over everything you've rated across the full 3 months.",
      },
    ],
  },
];
