import type { StudyPlanSeed } from "./types";

// Feature 51's 3 Study Plans — real itineraries across Learn, Practice, FF
// Collections, and the Playbook, not a question list alone (build-plan.md's
// own framing for why this is a real FF differentiator). Every href below
// points at a route that exists today: concept slugs/categories verified
// against scripts/seed/concepts.ts, playbook chapter slugs against
// content/interview-prep/playbook/**, Practice category slugs against
// features/practice/lib/practiceCategories.ts's PRACTICE_CATEGORIES.
export const STUDY_PLANS: StudyPlanSeed[] = [
  {
    slug: "1-week",
    title: "1 Week",
    durationLabel: "1 Week",
    hoursCommitment: "~2 hrs/day",
    description:
      "Cramming for a frontend interview coming up fast. Rapid-fire review of the highest-frequency questions, a focused deep dive into JavaScript, React, and Next.js, then a full day each on system design, behavioural prep, and your target company before the real thing.",
    orderIndex: 1,
    items: [
      {
        groupLabel: "Day 1",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        title: "FF 75 rapid review",
        description:
          "The 75 most-frequently-asked frontend interview questions, curated across JavaScript, React, and Next.js. Flag anything you can't answer confidently in under a minute — those are your weak spots for the rest of the week.",
      },
      {
        groupLabel: "Day 2",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        title: "FF JavaScript deep dive",
        description:
          "Full JavaScript runtime coverage — closures, the event loop, async patterns, prototypal inheritance. If your target role is JS-heavy, this is the collection to know cold.",
      },
      {
        groupLabel: "Day 3",
        itemType: "collection",
        href: "/interview-prep/ff-react",
        title: "FF React deep dive",
        description:
          "Hooks, rendering, component patterns, and performance — React interview questions asked at real companies, ranked by frequency.",
      },
      {
        groupLabel: "Day 4",
        itemType: "collection",
        href: "/interview-prep/ff-nextjs",
        title: "FF Next.js review",
        description: "Rendering strategies, routing, and the App Router — Next.js-specific questions most JavaScript-only prep skips entirely.",
      },
      {
        groupLabel: "Day 4",
        itemType: "practice-category",
        href: "/practice/react",
        title: "React coding reps",
        description: "Timed practice on real React coding challenges — custom hooks, state management, component patterns — to pair the theory with hands-on speed.",
      },
      {
        groupLabel: "Day 5",
        itemType: "playbook-chapter",
        refId: "frontend-system-design-playbook/why-frontend-system-design-is-different",
        href: "/interview-prep/playbook/frontend-system-design-playbook/why-frontend-system-design-is-different",
        title: "Why frontend system design is different",
        description: "How frontend system design interviews diverge from backend ones, and the framework this playbook builds on for the rest of the week.",
      },
      {
        groupLabel: "Day 5",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design",
        title: "FF Frontend System Design guides",
        description: "Rich, guided walkthroughs of real frontend system design prompts — infinite scroll, real-time collaboration, design systems, and more.",
      },
      {
        groupLabel: "Day 6",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/the-star-method-done-properly",
        href: "/interview-prep/playbook/behavioural-interview-playbook/the-star-method-done-properly",
        title: "The STAR method, done properly",
        description: "How to structure a behavioural answer so it lands — the concrete Action-to-Situation ratio most candidates get backwards.",
      },
      {
        groupLabel: "Day 6",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/building-your-personal-story-bank",
        href: "/interview-prep/playbook/behavioural-interview-playbook/building-your-personal-story-bank",
        title: "Build your personal story bank",
        description: "Turn your last few projects into 5-6 reusable STAR stories you can adapt on the fly to almost any behavioural prompt.",
      },
      {
        groupLabel: "Day 7",
        itemType: "company-guide",
        href: "/interview-prep/company-guides",
        title: "Target company guide",
        description: "Find your target company and review the real questions and challenges attributed to it — the single highest-leverage hour before an on-site.",
      },
      {
        groupLabel: "Day 7",
        itemType: "review-session",
        href: "/interview-prep/review",
        title: "Final spaced-repetition review",
        description: "A last spaced-repetition pass over everything you've rated this week — the questions you marked \"Need to review\" surface first.",
      },
    ],
  },

  {
    slug: "1-month",
    title: "1 Month",
    durationLabel: "1 Month",
    hoursCommitment: "~6 hrs/week",
    description:
      "A balanced, 4-week pass for candidates with a month of runway — one week each on foundations, hands-on practice, advanced React and system design, then a final week polishing behavioural, resume, and company-specific prep.",
    orderIndex: 2,
    items: [
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "javascript-runtime/hoisting-temporal-dead-zone",
        href: "/learn/javascript-runtime/hoisting-temporal-dead-zone",
        title: "Learn: Hoisting & the Temporal Dead Zone",
        description: "Start with your weakest fundamentals category. If that's JavaScript runtime behavior, this is the on-ramp.",
      },
      {
        groupLabel: "Week 1",
        itemType: "concept",
        refId: "browser-internals/dom-vs-bom",
        href: "/learn/browser-internals/dom-vs-bom",
        title: "Learn: DOM vs. BOM",
        description: "Foundational browser-internals concepts that show up in almost every frontend interview loop, in some form.",
      },
      {
        groupLabel: "Week 2",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        title: "Practice: JavaScript coding questions",
        description: "Hands-on coding reps — debounce/throttle, deep clone, custom event emitters — the frontend-engineering problems that show up in live-coding rounds.",
      },
      {
        groupLabel: "Week 2",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        title: "FF JavaScript review",
        description: "Pair your coding reps with the theory — full JavaScript runtime Q&A coverage.",
      },
      {
        groupLabel: "Week 3",
        itemType: "concept",
        refId: "react/jsx-virtual-dom",
        href: "/learn/react/jsx-virtual-dom",
        title: "Learn: JSX & the Virtual DOM",
        description: "React week starts here — the mental model every later React concept builds on.",
      },
      {
        groupLabel: "Week 3",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design",
        title: "FF Frontend System Design guides",
        description: "Start one guide relevant to your target role — infinite scroll and real-time collaboration are the two most commonly asked.",
      },
      {
        groupLabel: "Week 3",
        itemType: "playbook-chapter",
        refId: "frontend-system-design-playbook/a-repeatable-framework-for-frontend-system-design",
        href: "/interview-prep/playbook/frontend-system-design-playbook/a-repeatable-framework-for-frontend-system-design",
        title: "A repeatable framework for frontend system design",
        description: "The requirements-to-tradeoffs framework this playbook uses — apply it to the guide you just read.",
      },
      {
        groupLabel: "Week 4",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/the-star-method-done-properly",
        href: "/interview-prep/playbook/behavioural-interview-playbook/the-star-method-done-properly",
        title: "The STAR method, done properly",
        description: "Behavioural prep week — structure your answers before you write them.",
      },
      {
        groupLabel: "Week 4",
        itemType: "playbook-chapter",
        refId: "frontend-resume-playbook/frontend-specific-resume-structure",
        href: "/interview-prep/playbook/frontend-resume-playbook/frontend-specific-resume-structure",
        title: "Frontend-specific resume structure",
        description: "Tighten your resume against what frontend recruiters actually scan for, before you start applying.",
      },
      {
        groupLabel: "Week 4",
        itemType: "company-guide",
        href: "/interview-prep/company-guides",
        title: "Target company guide",
        description: "Filter down to real questions and challenges from your target company.",
      },
      {
        groupLabel: "Week 4",
        itemType: "review-session",
        href: "/interview-prep/review",
        title: "Spaced-repetition review",
        description: "A full pass over everything you've rated across the month.",
      },
    ],
  },

  {
    slug: "3-months",
    title: "3 Months",
    durationLabel: "3 Months",
    hoursCommitment: "~4 hrs/week",
    description:
      "A systematic, category-by-category pass through the full Learn curriculum with real weekly Practice reps, then a final month that shifts fully into interview mode — every FF Collection, all 5 Playbooks, and a target Company Guide.",
    orderIndex: 3,
    items: [
      // ── Month 1 — JS Runtime, Browser Internals, React, CSS ──
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/hoisting-temporal-dead-zone",
        href: "/learn/javascript-runtime/hoisting-temporal-dead-zone",
        title: "Learn: Hoisting & the Temporal Dead Zone",
        description: "Month 1 is JavaScript Runtime, Browser Internals, React, and CSS — one category per week, foundations first.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "concept",
        refId: "javascript-runtime/closures",
        href: "/learn/javascript-runtime/closures",
        title: "Learn: Closures",
        description: "The concept behind more \"gotcha\" interview questions than almost any other in JavaScript.",
      },
      {
        groupLabel: "Month 1 · Week 1",
        itemType: "practice-category",
        href: "/practice/javascript-runtime",
        title: "Practice: JavaScript coding questions",
        description: "Apply this week's concepts to real coding challenges before moving on.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "concept",
        refId: "browser-internals/dom-vs-bom",
        href: "/learn/browser-internals/dom-vs-bom",
        title: "Learn: DOM vs. BOM",
        description: "Browser Internals week — how the browser actually models a page.",
      },
      {
        groupLabel: "Month 1 · Week 2",
        itemType: "concept",
        refId: "browser-internals/event-delegation-bubbling-capturing",
        href: "/learn/browser-internals/event-delegation-bubbling-capturing",
        title: "Learn: Event Delegation, Bubbling & Capturing",
        description: "A near-guaranteed live-coding or whiteboard topic in any frontend loop.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/jsx-virtual-dom",
        href: "/learn/react/jsx-virtual-dom",
        title: "Learn: JSX & the Virtual DOM",
        description: "React week — start with the mental model, not the API surface.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "concept",
        refId: "react/usestate-useeffect-fundamentals",
        href: "/learn/react/usestate-useeffect-fundamentals",
        title: "Learn: useState & useEffect Fundamentals",
        description: "The two hooks every other React concept assumes you already understand well.",
      },
      {
        groupLabel: "Month 1 · Week 3",
        itemType: "practice-category",
        href: "/practice/react",
        title: "Practice: React coding questions",
        description: "Custom hooks, component patterns, and state — hands-on React reps.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "concept",
        refId: "css/the-box-model",
        href: "/learn/css/the-box-model",
        title: "Learn: The Box Model",
        description: "CSS week — the model every layout question, from Flexbox to Grid, builds on.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "concept",
        refId: "css/css-specificity",
        href: "/learn/css/css-specificity",
        title: "Learn: CSS Specificity",
        description: "The single most commonly misunderstood CSS interview topic — worth a real deep dive.",
      },
      {
        groupLabel: "Month 1 · Week 4",
        itemType: "practice-category",
        href: "/practice/css",
        title: "Practice: CSS questions",
        description: "Layout and specificity problems you can only get fast at through repetition.",
      },

      // ── Month 2 — TypeScript, Accessibility, Performance, System Design ──
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "concept",
        refId: "typescript/basic-types-inference",
        href: "/learn/typescript/basic-types-inference",
        title: "Learn: Basic Types, Inference & any/unknown/never",
        description: "Month 2 is TypeScript, Accessibility, Performance, and System Design.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "concept",
        refId: "typescript/interfaces-vs-type-aliases",
        href: "/learn/typescript/interfaces-vs-type-aliases",
        title: "Learn: Interfaces vs. Type Aliases",
        description: "A near-guaranteed question in any TypeScript-heavy interview loop.",
      },
      {
        groupLabel: "Month 2 · Week 5",
        itemType: "practice-category",
        href: "/practice/typescript",
        title: "Practice: TypeScript puzzles",
        description: "Type-level problems graded against the real TypeScript compiler, not string matching.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "concept",
        refId: "accessibility/aria-roles-and-semantic-html",
        href: "/learn/accessibility/aria-roles-and-semantic-html",
        title: "Learn: Semantic HTML & ARIA Roles",
        description: "Accessibility week — the topic most candidates skip prep for, and the one that stands out most when you don't.",
      },
      {
        groupLabel: "Month 2 · Week 6",
        itemType: "concept",
        refId: "accessibility/accessible-images-media",
        href: "/learn/accessibility/accessible-images-media",
        title: "Learn: Accessible Images & Media",
        description: "Concrete, checkable accessibility practices interviewers actually look for in a live-coding round.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "concept",
        refId: "performance/image-asset-optimization",
        href: "/learn/performance/image-asset-optimization",
        title: "Learn: Image & Asset Optimization",
        description: "Performance week — the easiest wins to talk through concretely in an interview.",
      },
      {
        groupLabel: "Month 2 · Week 7",
        itemType: "concept",
        refId: "performance/bundle-size-code-splitting",
        href: "/learn/performance/bundle-size-code-splitting",
        title: "Learn: Bundle Size & Code Splitting",
        description: "How to talk about performance like a senior engineer — with real levers, not vague claims.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "system-design/component-driven-architecture",
        href: "/learn/system-design/component-driven-architecture",
        title: "Learn: Component-Driven Architecture",
        description: "System Design week — how to structure a frontend codebase at scale.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "concept",
        refId: "system-design/api-design-data-fetching-strategy",
        href: "/learn/system-design/api-design-data-fetching-strategy",
        title: "Learn: API Design & Data-Fetching Strategy",
        description: "REST vs. GraphQL vs. WebSockets, and how to reason about the tradeoffs out loud.",
      },
      {
        groupLabel: "Month 2 · Week 8",
        itemType: "practice-category",
        href: "/practice/system-design",
        title: "Practice: Frontend system design questions",
        description: "Applied system-design problems to pressure-test the concepts from this week.",
      },

      // ── Month 3 — Interview mode ──
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "collection",
        href: "/interview-prep/ff-75",
        title: "FF 75 rapid review",
        description: "Month 3 shifts fully into interview mode — every FF Collection, all 5 Playbooks, and your target Company Guide.",
      },
      {
        groupLabel: "Month 3 · Week 9",
        itemType: "collection",
        href: "/interview-prep/ff-javascript",
        title: "FF JavaScript full review",
        description: "A complete pass over JavaScript Q&A, informed by 8 weeks of Learn and Practice behind you.",
      },
      {
        groupLabel: "Month 3 · Week 10",
        itemType: "collection",
        href: "/interview-prep/ff-react",
        title: "FF React full review",
        description: "React interview questions — hooks, rendering, and performance.",
      },
      {
        groupLabel: "Month 3 · Week 10",
        itemType: "collection",
        href: "/interview-prep/ff-nextjs",
        title: "FF Next.js review",
        description: "Rendering strategies, routing, and the App Router.",
      },
      {
        groupLabel: "Month 3 · Week 10",
        itemType: "system-design-guide",
        href: "/interview-prep/ff-system-design",
        title: "FF Frontend System Design guides",
        description: "Revisit your Month 2 System Design week with 2 more months of practice behind you.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "frontend-interview-playbook/how-frontend-interviews-are-structured",
        href: "/interview-prep/playbook/frontend-interview-playbook/how-frontend-interviews-are-structured",
        title: "How frontend interviews are structured",
        description: "A full week on all 5 Playbooks — start with the format overview.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "react-interview-playbook/what-react-interviews-really-test",
        href: "/interview-prep/playbook/react-interview-playbook/what-react-interviews-really-test",
        title: "What React interviews really test",
        description: "The React Interview Playbook's take on what actually gets scored in a React-focused loop.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "frontend-system-design-playbook/why-frontend-system-design-is-different",
        href: "/interview-prep/playbook/frontend-system-design-playbook/why-frontend-system-design-is-different",
        title: "Why frontend system design is different",
        description: "A refresher before your final system design reps.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "behavioural-interview-playbook/why-behavioral-rounds-exist",
        href: "/interview-prep/playbook/behavioural-interview-playbook/why-behavioral-rounds-exist",
        title: "Why behavioral rounds exist",
        description: "Understand what the round is actually evaluating before you rehearse answers for it.",
      },
      {
        groupLabel: "Month 3 · Week 11",
        itemType: "playbook-chapter",
        refId: "frontend-resume-playbook/what-recruiters-scan-for-in-eight-seconds",
        href: "/interview-prep/playbook/frontend-resume-playbook/what-recruiters-scan-for-in-eight-seconds",
        title: "What recruiters scan for in 8 seconds",
        description: "Finalize your resume before you start scheduling on-sites.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "company-guide",
        href: "/interview-prep/company-guides",
        title: "Target company guide",
        description: "Real questions and challenges from your target company — the final, highest-leverage prep step.",
      },
      {
        groupLabel: "Month 3 · Week 12",
        itemType: "review-session",
        href: "/interview-prep/review",
        title: "Final spaced-repetition review",
        description: "One last pass over everything you've rated across the full 3 months.",
      },
    ],
  },
];
